[tool.black]
line-length = 160
target-version = ['py310', 'py311']
include = '\.pyi?$'
exclude = 'contrib/scmaintools|\.venv|\.git|\.hg|\.mypy_cache|\.tox|\.venv|_build|buck-out|build|dist|node_modules|bower_components'